### ISSUE TITLE
Add n98-magerun2

### ISSUE THREAD

**Issue by avoelkl** [ModestCoders/magento2-dockergento#28]
Hi!

Would it be possible to add n98-magerun2 to the container?
What would be the best way to customize it myself (if not added out of the box)?

Thanks!

**Comment by danielozano** [comment]
Hi @avoelkl!

If you want to include n98/magerun2 in your project you just have to add it as dependency into your composer.json!

- (`dockergento setup` if you didn't setup the project)
- `dockergento start`
- `dockergento composer require n98/magerun2:^2.3`

And then you only've to run n98 inside the container: `dockergento exec vendor/bin/n98-magerun2`

Hope if helps, regards!

**Comment by avoelkl** [comment]
Ohhh man.... Thanks :D
I totally forgot about including it via composer. That helps, thanks :)

**Comment by danielozano** [comment]
@avoelkl no problem! You're welcome!
