### ISSUE TITLE
ERROR: .IOError: [Errno 2] No such file or directory: u'./docker-compose.yml'

### ISSUE THREAD

**Issue by WinstonN** [ModestCoders/magento2-dockergento#31]
Hello! 

I am sure I did something screwy on my end, but I am trying to initialise a new project and I am getting the error
```
ERROR: .IOError: [Errno 2] No such file or directory: u'./docker-compose.yml'

Docker is not properly configured. Please execute:

  dockergento setup
```
when I run dockergento setup I get

```
Setting up dockergento config files
 > cp /../../../magento2-dockergento/bin/../config/dockergento/ -> config/dockergento
cp: cannot stat '/../../../magento2-dockergento/bin/../config/dockergento/': No such file or directory
```
This did work previously, and I am sure this is something I did wrong, but can you help me track it down?

Thank you!

**Comment by jalogut** [comment]
Hi @WinstonN 

Please go inside the folder where you are executing `dockergento setup` and let me know the output of the following commands:

* `pwd`
* `which dockergento` 
* `ls -lah /../../../magento2-dockergento/bin/../`
* `ls -lah /../../../magento2-dockergento/bin/../config/dockergento/`
* `git describe --tags --abbrev=0`

**Comment by WinstonN** [comment]
hey @jalogut 

pwd
```
/tmp/dockergento-test
```
which dockergento
```
/usr/local/bin/dockergento
```

```
[14:49] /tmp/dockergento-test ❯❯❯ ls -lah
total 28K
drwxrwxr-x  3 win  win  4.0K Jan  3 14:48 .
drwxrwxrwt 29 root root  20K Jan  3 14:47 ..
drwxrwxr-x  2 win  win  4.0K Jan  3 14:48 config
[14:50] /tmp/dockergento-test ❯❯❯ ls -lah config 
total 8.0K
drwxrwxr-x 2 win win 4.0K Jan  3 14:48 .
drwxrwxr-x 3 win win 4.0K Jan  3 14:48 ..
[14:50] /tmp/dockergento-test ❯❯❯ 
```

```
[14:48] .../projects/magento2-dockergento ❯❯❯ git describe --tags --abbrev=0
3.3.0
```

Let me know if you need anything else

**Comment by WinstonN** [comment]
Hi @jalogut  

I am not sure what happened there, but you were spot on!
I think I might have moved dockergento instead of copying it when I moved it to /usr/local/bin/dockergento? 

I copied it back to that folder and we're good to go. Could that have been the issue?

I just want to say thank you for helping me. Dockergento is so amazing to work with <3

**Comment by jalogut** [comment]
Hey

I am glad you managed to fix the issue. Yes, moving dockergento but not the config folder might have been the issue. Normally you should create a symlink to `/usr/local/bin/dockergento` instead of moving it.

I close this issue then. Cheers!
