### ISSUE TITLE
PHP 7.2 support for Magento 2.3

### ISSUE THREAD

**Issue by erfanimani** [ModestCoders/magento2-dockergento#35]
I believe Magento 2.3 supports PHP 7.2 out of the box now and it would be great if `dockergento setup` would allow you to pick PHP 7.2.

**Comment by danielozano** [comment]
Hi @erfanimani thank you for giving a shot to this tool! I've created a PR, until it's merged maybe you can try to use it: #36

Hope it helps, anything you need please let me know!

**Comment by danielozano** [comment]
@erfanimani You can also update your actual setup modifying your docker-compose file, just replace the actual image with the new php 7.2 images:
* For node container:
```yaml
  node:
    image: modestcoders/node-php:node8-php7.2
```
* For phpfpm container:
```yaml
  phpfpm:
    image: modestcoders/php:7.2-fpm-1
```

Then just run `dockergento rebuild`

**Comment by erfanimani** [comment]
Thank you! :) That worked perfectly.
