### ISSUE TITLE
Parallel Package Downloads

### ISSUE THREAD

**Issue by pocallaghan** [ModestCoders/magento2-dockergento#37]
Magento is built up from a lot of packages. Have you considered installing the composer plugin hirak/prestissimo into the box, it drastically improves the speed of installation.

**Comment by jalogut** [comment]
Hi @pocallaghan 

No we have not considered that, sorry. If you need that, you can add the dependency in the `composer.json` file of your project. Would that work for you?

**Comment by ihor-sviziev** [comment]
Actually as ~/.composer directory is mounted inside container - you could run `dockergento composer global require hirak/prestissimo`
It should work

**Comment by danielozano** [comment]
I'm closing this issue! 
It's not dockergento domain, you can add whatever you want to your project once it's been created!

Thanks a lot!
