### ISSUE TITLE
Nginx: 413 – Request Entity Too Large Error 

### ISSUE THREAD

**Issue by Ahmed-Ayman** [ModestCoders/magento2-dockergento#38]
I have got this error `Nginx: 413 – Request Entity Too Large Error` while uploading a json file to the server, that is some imports data imports for some mega menu that I just started using.
anyways I'm getting this issue now and finally found out that it's a problem with ngnix configs according to [this](https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/).
I will submit a PR for it now!

**Comment by jalogut** [comment]
Hi @Ahmed-Ayman 

As I mentioned on your PR https://github.com/ModestCoders/magento2-dockergento/pull/39 , you can add your code in `config/dockergento/nginx/conf/default.conf`:

```
server {
  # ...
  # set client body size to 2M 
  client_max_body_size 2M;
  # ...
}
```

Thanks for providing a solution, so other users having the same problem can find it here ;)

**Comment by Ahmed-Ayman** [comment]
thank you @jalogut  :)
