### ISSUE TITLE
Your session has expired

### ISSUE THREAD

**Issue by wkaminsk** [ModestCoders/magento2-dockergento#41]
Hi,
thank you for great tool.

Seems there's a problem with session.
I created new Magento 2.2.8  project, created simple product. Went to product page and tried to add a product.

Magento is giving an issue: http://prntscr.com/n3nelt

Docker - http://prntscr.com/n3ndbf

Thanks!

**Comment by danielozano** [comment]
Hi, I'm not able to reproduce this issue, I've never faced it and I'm using this tool quite long. Do you've more information about it?

I'm not sure if  it's related to the tool!
