### ISSUE TITLE
Switch xdebug remote port to 9000

### ISSUE THREAD

**Issue by ihor-sviziev** [ModestCoders/magento2-dockergento#49]
Right now Dockergento using custom 9001 port for xdebug. 
https://github.com/ModestCoders/magento2-dockergento/blob/1e7b9b510413d3a8a48f17cd15b5c3ff98053c7b/docs/xdebug_phpstorm.md

https://github.com/ModestCoders/dockerfiles/blob/df68a4521976c77c763de4b340edd09f69dbfdeb/php/7.1-fpm/conf/xdebug.ini#L6

Is there any reason to have custom port, instead of default one - 9000? I think switching to 9000 port will lead to easier xdebug configuration

**Comment by danielozano** [comment]
Hi @ihor-sviziev I think there is no specific version for using this port, but maybe @jalogut  can confirm that!

If you try the 9000 port and find no issues at all please tell us and we could change it as default! Of this way you won't need to update it in phpstorm settings.

**Comment by jalogut** [comment]
Hi @ihor-sviziev well actually there is a reason for that. Our php images use port 9000 for `FastCGI` connections.

See line 36 here: https://github.com/ModestCoders/dockerfiles/blob/master/php/7.2-fpm/conf/www.conf

**Comment by ihor-sviziev** [comment]
I think it's not a big deal and not really related.
1. It listens 9000 port on php-fpm container and not forwarded to host machine
2. nginx actually working with php fpm using unix socket, I guess using 9000 port there could be safely removed
https://github.com/ModestCoders/dockerfiles/blob/master/nginx/1.13/conf/default.conf#L2

**Comment by ihor-sviziev** [comment]
Any updates?
@danielozano @jalogut

**Comment by danielozano** [comment]
Hi @ihor-sviziev If phpstorm uses port 9000 by default, and we don't need to use it for fastcgi because nginx is already using unix socket I don't see any reason to move XDEBIG to port 9001.

I'll work on it! Thanks!

**Comment by ihor-sviziev** [comment]
Basically in xdebug 3 there was changed default port to 9003, it will be switched to this new port in https://github.com/ModestCoders/dockerfiles/pull/21 and https://github.com/ModestCoders/magento2-dockergento/pull/83.
I'm closing this issue as not relevant anymore.
