### ISSUE TITLE
Dockerize projoct

### ISSUE THREAD

**Issue by ruospo** [ModestCoders/magento2-dockergento#59]
Hi, after make dockergento setup and upload the sql dump of db, magento show Autoload Error.
I missing any step?

I use Osx Catalina.

tnx for help

**Comment by gallyamov** [comment]
I think you missed the composer install step.

**Comment by danielozano** [comment]
Hi! @ruospo !! @gallyamov ir right, you are missing: `dockergento composer install`

**Comment by ruospo** [comment]
tnx !! yes missing dockergento composer install 

dockergento is amazing
