### ISSUE TITLE
Missing extension ext-sockets

### ISSUE THREAD

**Issue by n0ni0** [ModestCoders/magento2-dockergento#61]
Hi,

I tried to install Magento with the contribution version (I think it will also fail in a no contribution installation) and the ext-sockets extension is missing.

<img width="904" alt="Captura de pantalla 2019-12-10 a las 21 10 02" src="https://user-images.githubusercontent.com/8030309/70565463-79271100-1b92-11ea-9cb2-1a8753a2a089.png">

**Comment by manuelgarciasbricomart** [comment]
@jalogut can you share the Dockerfile you used to generate the "modestcoders" images? That way we can build our own images starting from the initial setup that you've already defined. Thanks

**Comment by danielozano** [comment]
Hi @manuelgarciasbricomart the images are also open: https://github.com/ModestCoders/dockerfiles

Hope it helps!

**Comment by manuelgarciasbricomart** [comment]
Great @danielozano I will take a look at it. Thanks!

**Comment by danielozano** [comment]
@manuelgarciasbricomart I close the issue, the images are updated with sockets extension.

Thanks for your help!
