### ISSUE TITLE
Feature request: Add support for php7.3

### ISSUE THREAD

**Issue by duckchip** [ModestCoders/magento2-dockergento#65]
Hi guys,

Magento2.3 now support PHP 7.3.
Would it be possible to make dockergento compatible with this new version? :)

Thx in advance!

Kind regards

Tristan

**Comment by danielozano** [comment]
Hi! @duckchip I've added support for php 7.3: https://github.com/ModestCoders/dockerfiles/tree/master/php/7.3-fpm

I'll update the setup command in order to add it to the available default versions, in the meanwhile you can update your own docker-compose.yml and rebuild!

Thank you!

**Comment by danielozano** [comment]
@duckchip the php 7.3 version should be available when you use the setup command! Let me know if it works!

Thank you in advance!

**Comment by danielozano** [comment]
Closing because of  inactivity. The funcionality has ben already implemented, if not reopen the issue!
