### ISSUE TITLE
Feature request: add support for Magento 2 EE

### ISSUE THREAD

**Issue by arendarenko** [ModestCoders/magento2-dockergento#70]
Currently dockergento has only Magento 2 CE edition.
I think it's a good idea to add ability to choose CE/EE edition as additional step during project create.

**Comment by danielozano** [comment]
Hi! @arendarenko thanks for using this tool and sorry for the late response, I don't have much time lately! You're right atm there is no way to initialize an EE project, it could be really good to have it!

**Comment by arendarenko** [comment]
hi @danielozano 
I already added the implementation. Please review #73

**Comment by danielozano** [comment]
Already merged #73 thanks a lot for you contribution!
