### ISSUE TITLE
modestcoders/node-php:node8-php7.3 is not avalible

### ISSUE THREAD

**Issue by appicsandbox** [ModestCoders/magento2-dockergento#77]
When i run the $ dockergento grunt exec<theme> or $dockergento grunt watch i get the following:
```
➜  $ dockergento grunt watch
Starting server_db_1            ... done
Starting server_elasticsearch_1 ... done
Starting server_phpfpm_1        ... done
Pulling node (modestcoders/node-php:node8-php7.3)...
ERROR: manifest for modestcoders/node-php:node8-php7.3 not found: manifest unknown: manifest unknown
```

So this is an error that node8-php7.3 is not available. When I check this on https://github.com/ModestCoders/dockerfiles/tree/master/node-php, 7.3 seems not existing. When the docker-compose.yml, rule 38 to     image: modestcoders/node-php:node8-php7.2 it works. I do get other errors after that, so this might not be a solution. Just pointing out that something is wrong here?

**Comment by appicsandbox** [comment]
To be more precise. I get these php errors when running grunt:

```
➜ server git:(d36c542) ✗ dockergento grunt exec:all --force
Starting server_db_1            ... done
Starting server_elasticsearch_1 ... done
Starting server_phpfpm_1        ... done
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.

audited 992 packages in 5.754s
found 79 vulnerabilities (30 low, 16 moderate, 33 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Running "exec:all" (exec) task
grunt --force clean:blank
>> PHP Parse error:  syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting '-' or identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING) in /var/www/html/app/bootstrap.php on line 41
>> Exited with code: 255.
>> Error executing child process: Error: Process exited with code 255.
Warning: Task "exec:all" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2020-05-29 08:45:30 UTC-0)
loading tasks       96ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 69%
loading grunt-exec   2ms  ▇▇ 1%
exec:all            40ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 29%
Total 139ms

➜  server git:(d36c542) ✗
```

So i'm not sure if those are related to the changing of the PHP version, but it seems to have a relation. Any ideas for a solution?

**Comment by appicsandbox** [comment]
Temp solution worked for me: build Docker image, based on modestcoders/node-php:node8-php7.2, but changed 7.2 to 7.3, and used this Docker image in the dockergento generated docker-compose.yml as the node image.

**Comment by danielozano** [comment]
Hi! @appicsandbox image tag has been added today! If you want you can try to download it!

PR: https://github.com/ModestCoders/dockerfiles/pull/17
Image: https://github.com/ModestCoders/dockerfiles/tree/master/node-php/node8-php7.3

**Comment by danielozano** [comment]
I'm closing this issue, if the problem remains please feel free to reopen it!
Thanks!
