### ISSUE TITLE
how to set it as production

### ISSUE THREAD

**Issue by thunderwin** [ModestCoders/magento2-dockergento#79]
how to set it as production

**Comment by riccardofinkers** [comment]
dockergento magento deploy:mode:show to see what mode it is set on

To production:
dockergento magento deploy:mode:set production

**Comment by danielozano** [comment]
Hi @thunderwin if that doesn't work for you, you can also force it using NGINX env variables changing this line: https://github.com/ModestCoders/magento2-dockergento/blob/master/config/dockergento/nginx/conf/default.conf#L21

I'm closing the issue, if the problem remains please feel free to reopen it!
