### ISSUE TITLE
PHP 7.4 Support

### ISSUE THREAD

**Issue by quyendam2612** [ModestCoders/magento2-dockergento#80]
Hello guys,

As Magento 2.4.0 just released it recommends to run the new Magento installation with PHP 7.4. Is there any plan to support this php version in the near future?

Thanks,

**Comment by VictorEfimov** [comment]
I think with PHP 7.4 also elasticsearch7 needed.

**Comment by danielozano** [comment]
Hi! @quyendam2612 I've just added php 7.4 to the setup command, and its also available under the tag: modestcoders/php:7.4-fpm.

@VictorEfimov elasticsearch was added with this release: (4.0) https://github.com/ModestCoders/magento2-dockergento/releases/tag/4.0.0

If you have any issues just let me know.

**Comment by danielozano** [comment]
Closing the issue, if you've any trouble upgrading to php 7.4 please reopen it

Thanks!
