### ISSUE TITLE
sample data install fails / composer error php 7.2 magento v 2.3.2

### ISSUE THREAD

**Issue by alainseys** [ModestCoders/magento2-dockergento#88]
Hy, i have installed magento 2.3.2 with your tool the basics are find but if i want to install the magento sample i get the following error.

php version used: 7.2

Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 4096 bytes) in /var/www/html/vendor/composer/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

i checked the php memory this is the output 
`biopack dockergento exec php -r "echo ini_get('memory_limit').PHP_EOL;"
2G`

then i noticed the container is still running composer v1 when i tried upgrading this to v2 i got the following error:
`biopack dockergento exec composer self-update --2

  [Symfony\Component\Console\Exception\RuntimeException]
  The "--2" option does not exist.
`

how can i upgrade composer (preferable) or install the sample files, please advise me

**Comment by sanaeefar-saeed** [comment]
Hey @alainseys, 
No need to update the composer.
All you need to do is increasing the PHP memory_limit.
Already discussed here 
https://github.com/ModestCoders/magento2-dockergento/issues/34
Anyway, I'll summarize it:
1- change 
docker-compose.yml->services->phpfpm->image: modestcoders/php:7.2-fpm
to
build: ./config/dockergento/phpfpm/

2- create following files 
./config/dockergento/phpfpm/Dockerfile with below content 
```
FROM modestcoders/php:7.4-fpm
USER root
COPY conf/custom.ini /usr/local/etc/php/
COPY conf/custom.ini /usr/local/etc/php/conf.d/
USER app:app
```
./config/dockergento/phpfpm/conf/custom.ini with below content

```
memory_limit = 8G
max_execution_time = 36000
```
3- run dockergento rebuild
4- to verify run:
 4-1 docker-compose exec phpfpm bash
 4-2 php -i | grep "memory_limit"
you'll get **memory_limit => 8G => 8G** 
and now you should be able to run the sample data command

**Comment by alainseys** [comment]
Hy @sanaeefar-saeed  thanks somewhere i missed that post tested this out and indeed this works like expected thanks mate
